- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
    
  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - mc
          - screen
          - neofetch
          - net-tools 
          - tree

    - name: create ansible user
      user:
        name: ansible
        system: yes
   
    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dst: /home/redey/.bashrc
        owner: redey
        group: redey

    - name: copy .screenrc file
      copy:
        src: files/screenrc
        dst: /home/redey/.screenrc
        owner: redey
        group: redey

    - name: copy .vimrc file
      copy:
        src: files/vimrc
        dst: /home/redey/.vimrc
        owner: redey
        group: redey

    - name: install cron job (ansible-pull)
      cron:
        user: ansible
        name: "ansible provision"
        minute: "*/10"
        job: "/usr/bin/ansible-pull -o -U https://github.com/aredey/ansible_pull > /dev/null"

