- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
    
  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - mc
          - screen
          - neofetch
          - net-tools 
          - tree

    - name: create ansible user
      user:
        name: ansible
        system: yes
   
    - name: append .bashrc file
      blockinfile: 
        path: /home/redey/.bashrc
        block: |
          alias egrep='egrep --color=auto'
          alias fgrep='fgrep --color=auto'
          alias grep='grep --color=auto'
          alias q='exit'
          alias ipconfig='ip -4 a | egrep '\''^[0-9]+:.*:|inet\ .*/'\'''

    - name: copy .screenrc file
      copy:
        src: files/screenrc
        dest: /home/redey/.screenrc
        owner: redey
        group: redey

    - name: copy .vimrc file
      copy:
        src: files/vimrc
        dest: /home/redey/.vimrc
        owner: redey
        group: redey

    - name: install cron job (ansible-pull)
      cron:
        user: ansible
        name: "ansible provision"
        hour: "*"
        job: "/usr/bin/ansible-pull -o -U https://github.com/aredey/ansible_pull > /dev/null"

